apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: example-ingress
  annotations:
    nginx.ingress.kubernetes.io/rewrite-target: /$2
spec:
  rules:
    - host: mediawiki.hopto.org
      http:
        paths:
          - pathType: Prefix
            path: /jira
            backend:
              service:
                name: jira
                port:
                  number: 8080
       
