apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: mediawiki-ingress
spec:
  rules:
  - host: mediawiki.hopto.org
    http:
      paths:
      - pathType: Prefix
        path: "/"
        backend:
          service:
            name: mediawiki
            port:
              number: 80
